### ISSUE TITLE
LDAP support Documentation

### ISSUE THREAD

**Issue by bugzy** [docpht/docpht#12]
A quick search through the repo suggests that LDAP authentication may be possible[1]. Is that the case? If so where can I find documentation to get it going?
[1] https://github.com/docpht/docpht/blob/d3cadfd36867f3248d9c09cecc7fbaa09a5b0d32/vendor/sebastian/resource-operations/src/ResourceOperations.php
  - DocPHT version: 1.0.0
  - PHP version: 7.2
  - Platform: Linux
  - OS: Fedora 30
  - Browser: Firefox

**Comment by kenlog** [comment]
Hi @bugzy this is currently not expected or documented. Anyway, if you are in need and you have the ability to implement it, you can make PR.
