### ISSUE TITLE
How to remove block from page?

### ISSUE THREAD

**Issue by turbopixel** [docpht/docpht#14]
Hy there!
first: thank you for this great documentation software!

My question: I created a page and add some blocks into the page. Now, I will remove a block on a page. But there is no option for that, right?

![grafik](https://user-images.githubusercontent.com/15839724/72722172-fd02ee80-3b7d-11ea-94a9-0773fab6fdf2.png)

**Comment by turbopixel** [comment]
I see there are hidden buttons in every block:

![grafik](https://user-images.githubusercontent.com/15839724/72722532-d8f3dd00-3b7e-11ea-84c6-033ba4eb4241.png)

I think the visibility is a bug.

**Comment by kenlog** [comment]
Hi @turbopixel and welcome, you can remove an element by hovering over the end of each element to show hidden buttons, however, this is not a bug.
![remove](https://user-images.githubusercontent.com/11728231/72724100-b1067880-3b82-11ea-9017-a89ce68046e3.gif)

**Comment by turbopixel** [comment]
Thanks for your answer. I thought they always had to be visible (without hovering).
