### ISSUE TITLE
Renaming topics and updating issues

### ISSUE THREAD

**Issue by MrksHfmn** [docpht/docpht#15]
thanks a lot for this great application! and it works wonderfully :) is there a way to edit topics? rename them without deleting? Updating works in general, but it only updates the content not the tree structure

**Comment by kenlog** [comment]
Hello @MrksHfmn and welcome, I'm glad this application is useful to you. 
This feature will be introduced in the next release.
Currently the only way is to rename manually, identifying the files inside the folders 'data' & 'pages' and updating the new routes in data/pages.json 
I hope I was helpful.
