### ISSUE TITLE
PHP8 Callable error on DocPHT\Controller\LoginController -> login 

### ISSUE THREAD

**Issue by KoljaL** [docpht/docpht#23]
## Expected Behavior
Login after installation

## Actual Behavior
Callable error on DocPHT\Controller\LoginController -> login 

## Steps to Reproduce the Problem

  1. download, unzip & upload to webspace
  2. do the installation form
  3. get this error after enabling debug in index.php 

## Specifications

  - DocPHT version:
  - PHP version: 1.3.2
  - OS: Ubuntu
  - Browser: FF

**Comment by creecros** [comment]
are you legit using php version 1.3.2?

**Comment by KoljaL** [comment]
Yes, I downloaded yesterday the release from 14.01.2020.

These are the first lines of the CHANGELOG.md on my webspace:

```md
# Changelog    

## [1.3.2] - 2020-01-14

### Fixed
- Fix allowed the reading of the images in data folder
```

Before enabling the debug output in the index.php, I got just a blank site.

**Comment by creecros** [comment]
I'm sorry, what I meant was, what version of PHP are you using.

**Comment by KoljaL** [comment]
Sorry, I was too fast - two times.

  - DocPHT version: 1.3.2
  - PHP version: 8.0.6

edit:
After changing to PHP 7.4 it works

**Comment by creecros** [comment]
yes makes sense. I was about to suggest downgrading, since php 8 wasn't out when we wrote it.
