### ISSUE TITLE
DocPHT Not Working On Mobile Browser

### ISSUE THREAD

**Issue by guillaumesoucy94** [docpht/docpht#28]
## Expected Behavior

To see the login fields.

## Actual Behavior

Login field are not showing on mobile but it works on desktop.

![DB680A56-F9B1-4FD8-9A91-3CE5B170E0AC](https://user-images.githubusercontent.com/22561876/152483976-58421d7d-8368-4327-8abe-0e768289e277.png)

## Steps to Reproduce the Problem

  1. Going on the instance with an iPhone
  2.
  3.

## Specifications

  - DocPHT version: Latest Version
  - PHP version: 7.4
  - Platform: x64
  - OS: Ubuntu Server 20.04 LTS
  - Browser: Mozilla Firefox

**Comment by kenlog** [comment]
Hi @guillaumesoucy94 probably because there are no pages, try to create the first one ... At least one as set as home
