### ISSUE TITLE
Uncaught Exception: Callable error

### ISSUE THREAD

**Issue by s22-tech** [docpht/docpht#30]
I downloaded the latest version of the script and manually installed it on my server.  Going to the URL, I got the installation screen and filled in all the fields.  Then the browser went to www.server.com/login and gave me a blank screen.  So I turned on show errors in /index.php and got the following error:

```
PHP Fatal error:  Uncaught Exception: Callable error on DocPHT\Controller\LoginController -> login ! in /home/projects/docs/vendor/nezamy/route/system/Route.php:638
Stack trace:
#0 /home/projects/docs/vendor/nezamy/route/system/Route.php(598): System\Route->callback(Array, Array)
#1 /home/projects/docs/index.php(95): System\Route->end()
#2 {main}
  thrown in /home/projects/docs/vendor/nezamy/route/system/Route.php on line 638
```
This was also printed to the error log:
```
temp/install/partial/footer.php
temp/install/partial/head.php
```
The install instructions look pretty basic, so I don't think I missed anything.  Hopefully I can get this running, as I was really looking forward to seeing it in action.  😀

Thanks!

## Specifications

  - DocPHT version: 1.3.2
  - PHP version: 8.0.18
  - Platform: CentOS 7
  - OS: MacOS 10.15.7
  - Browser: Firefox Developer

**Comment by kenlog** [comment]
Hi @s22-tech PHP version 8 is not currently supported. PHP 7.4 it works
