### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by taofikanwart** [docpht/docpht#31]
![image](https://user-images.githubusercontent.com/13691720/171807514-64f7736d-fa26-4d50-92d7-fc0f17edde0a.png)
help, i cant install on my laptop, only show blank

**Comment by taofikanwart** [comment]
![image](https://user-images.githubusercontent.com/13691720/171812639-78178522-560c-4eca-bb7d-a43e28c683ea.png)

on other laptop

**Comment by kenlog** [comment]
Hi @taofikanwart 

**Prerequisites**
1. Make sure the version you are using is at most PHP / 7.4.29
2. apache mod_rewrite and mod_headers enable

**Comment by taofikanwart** [comment]
thanks itworks when i use php 7.4.29
