### ISSUE TITLE
404 Not Found OR HTTP ERROR 500

### ISSUE THREAD

**Issue by dangerstudios** [docpht/docpht#32]
## Expected Behavior
To be directed to the main page

## Actual Behavior
404 Not Found OR HTTP ERROR 500... Probably an .htaccess issue? not sure

## Steps to Reproduce the Problem

  1. Copy release folder contents to server 
  2. fill out the install page
  3. hit install button 

## Specifications

  - DocPHT version: 1.3.2
  - PHP version: PHP 8.1  
  - Platform: default LAMP stack on cloudways 
  - OS: linux
  - Browser: Chrome latest

**Comment by kenlog** [comment]
Hi @dangerstudios 

Prerequisites

    Make sure the version you are using is at most PHP / 7.4.29
    apache mod_rewrite and mod_headers enable
