### ISSUE TITLE
Fatal PHP mail error

### ISSUE THREAD

**Issue by Shikachuu** [docpht/docpht#6]
## Expected Behavior
Mail has been sent succesfully message or something like that

## Actual Behavior
```
Fatal error: Uncaught Error: Class 'DocPHT\Form\SendmailMailer' not found in /var/www/app/src/forms/AddUserForm.php:105 Stack trace: #0 /var/www/app/src/controller/AdminController.php(47): DocPHT\Form\AddUserForm->create() #1 [internal function]: DocPHT\Controller\AdminController->addUser() #2 /var/www/app/vendor/nezamy/route/system/Route.php(651): call_user_func_array(Array, Array) #3 /var/www/app/vendor/nezamy/route/system/Route.php(598): System\Route->callback(Array, Array) #4 /var/www/app/index.php(92): System\Route->end() #5 {main} thrown in /var/www/app/src/forms/AddUserForm.php on line 105
```

## Steps to Reproduce the Problem

  1. click on "create  a user"
  2. fill in the form
  3. click "add new user"

## Specifications

  - DocPHT version: v1.0.0
  - PHP version: 7.3.10-r0
  - Platform: Docker
  - OS: i use arch BTW
  - Browser: Firefox 69

**Comment by creecros** [comment]
For docker, the easiest way to send mail is using the smtpmailer. You will need to go into the config.php and enable it, and configure it.

**Comment by Shikachuu** [comment]
Thanks for the response,
For my oppinion it needs a better explonation in the README.md, I think I will do an another pull request :)

**Comment by creecros** [comment]
I can agree with that :)
